// Package declaration for the entity.AISnippet package
package entity.AISnippet;

// Interface declaration for AISnippet
public interface AISnippet {
    // Method to set the question associated with the snippet
    void setSnippetQuestion(String question);

    // Method to set the response generated by the AI for the snippet
    void setResponse(String response);

    // Method to retrieve the question associated with the snippet
    String getSnippetQuestion();

}
